### ISSUE TITLE
Request: Example of dragging object fixed in a point

### ISSUE THREAD

**Issue by D3m0n92** [immemorable-moniker/UnityXRGrabAndClimb#1]
Really very useful! Can you create a sample scene for dragging an object fixed in a point? (Maybe a lever, or for example being able to raise a gate or open a door)

**Comment by jackpritz** [comment]
I'll need to do that for the game I'm working on.  I've not gotten to it yet, but there's 2 ways I'm considering:
1) Use joints, similar to how VRTK does it
2) drive the rotation more directly.

In my experience, joints can be fidget-y.  Maybe if I start from scratch and spend some quality time with them I can figure out how to use them right.

**Comment by jackpritz** [comment]
004a628d1b4d3b8b4ce1e584a8a3c521515e5f49 adds a tiny door to the sample scene.  The door only moves when the JointManipulator is grabbed, which may or may not be desired.

If you unlock the position on the JointManipulator's rigidbody the door can be pushed with physics, and thrown around its hinge joint.  However, if you try to pull the door too far past its constrained rotation it will fling itself back in the other direction.  This fling force comes from when the hand's fixedjoint is broken due to too much force.  Perhaps it could be specifically nullified in script when Joint.OnJointBreak() fires.

**Comment by jackpritz** [comment]
4e47b8d4e1ec704fbe046bfec35f2681e20b27a5 adds a "physicsy" tiny door to show what unlocking the JointManipulator's rigidbody position does.

**Comment by jackpritz** [comment]
![physicsy_door](https://user-images.githubusercontent.com/5726183/52688389-21d0f980-2f0b-11e9-9d89-8bebc0f1791d.gif)
This gif shows the one behavior I don't like about the "physicsy" door.  This snap occurs when the JointManipulator is pulled too far and the hand's grab joint is broken.  I believe the force for the snap occurs because the JointManipulator's joint is pulling it back.  I'm not sure how best to prevent this from happening.  Maybe if the hand's grab joint was put on the HeldObject instead of the hand's gameobject?

Since I'll probably use the non-physicsy door for my own project, I will leave solving the snap as an exercise for the reader for now.  It might bug me enough to return to later.
